### PR TITLE
Add support for dynamically loaded images and strictlybetter.eu

### PR DESCRIPTION
**Pull request by Dankirk**
Add support for dynamically loaded images and [https://www.strictlybetter.eu](https://www.strictlybetter.eu)

DOM edits are monitored by MutationObserver class. 
hostMap in main.js has a new attribute 'observer', which is a selector to find DOM nodes that should be monitored for dynamic changes, so decklist buttons can be added to new content. If no 'observer' attribute exists for the host, no DOM change monitoring is done.

### CODE REVIEW

**Comment by devinrieger** [comment]
Hey thanks for the PR! I found mutationObserver to be unreliable, especially on EDHRec. Sometimes it would trigger, sometimes it wouldn't. So I went oldschool and as icky as it feels decided to use an interval and just check the number of card elements that have been added. I already pushed that change up so this PR is gonna have a bunch of merge conflicts.

I'll gladly add support for strictlybetter if you want to break that out into its own PR.

**Comment by devinrieger** [comment]
Also I like how you broke out the callback into `addButtons`, if you want to take another crack at that after the refactor I did please feel free!

**Comment by devinrieger** [comment]
PS @Dankirk I want to release 1.1 today to the extension store so please let me know if you'd like to get any changes in.

**Comment by Dankirk** [comment]
Ah, how unfortunate with the mutationObserver. I'll make a separate PR for strictlybetter. The addButtons is quite similiar to your initIcons, so I'll leave it as is.

Edit: New PR at #7

**Pull request closed without merging**
